{{- if .Values.projects }}
{{- range $project := .Values.projects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $project.name }}
  namespace: {{ $project.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "26"
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  roles:
    - name: {{ $project.role }}
      policies:
        - 'p, proj:{{ $project.name }}:{{ $project.role }}, applications, get, {{ $project.name }}/*, allow'
        - 'p, proj:{{ $project.name }}:{{ $project.role }}, applications, create, {{ $project.name }}/*, allow'
        - 'p, proj:{{ $project.name }}:{{ $project.role }}, applications, update, {{ $project.name }}/*, allow'
        - 'p, proj:{{ $project.name }}:{{ $project.role }}, applications, delete, {{ $project.name }}/*, allow'
{{- end }}
{{- end }}
