---
- name: Gather Cluster Info.
  gather_facts: false
  hosts: 'localhost'
  tasks:
  - name: Determine Host
    shell: "oc cluster-info | head -n 1 | sed 's/^.*https...api//' | sed 's/.6443.*$//'"
    register: cluster_response
  - name: Set Dev Spaces Instance
    set_fact:
      cluster_base_url: "{{ cluster_response.stdout }}"
  - debug: var=cluster_response.stdout_lines
- name: Customize Software Template
  gather_facts: false
  hosts: 'localhost'
  tasks:
  - name: Reset Local
    ansible.builtin.file:
      path: ../../../software-templates
      state: absent
  - name: Clone the Fork of software-templates
    block:
      - name: Clone the Fork of software-templates using SSH
        ansible.builtin.git:
          repo: git@github.com:{{ lookup('ansible.builtin.env', 'GITHUB_ORGANIZATION') }}/software-templates.git
          dest: ../../../software-templates
        environment:
          GIT_TERMINAL_PROMPT: 0
    rescue:
      - name: Retry Clone the Fork of software-templates using HTTPS
        ansible.builtin.git:
          repo: https://github.com/{{ lookup('ansible.builtin.env', 'GITHUB_ORGANIZATION') }}/software-templates.git
          dest: ../../../software-templates
        environment:
          GIT_TERMINAL_PROMPT: 0
  - name: Insert Cluster Information
    shell: |
      cd ../../../software-templates
      sed "s/\.cluster-[a-zA-Z0-9]*\.[a-zA-Z0-9]*\.sandbox[a-zA-Z0-9]*\.opentlc\.com/{{ cluster_base_url }}/g" ./scaffolder-templates/quarkus-web-template/template.yaml > output.txt && mv output.txt ./scaffolder-templates/quarkus-web-template/template.yaml
      git add -A
      git commit -m "initial customization"
      git push
    environment:
        LC_CTYPE: C
        LANG: C
    register: result
  - debug: var=result.stdout_lines
